
var oldJson = {
    "key": "PQR",
    "points": [{
        "lid": "adnw1",
        "latitude": "46.617500",
        "longitude": "-123.276389",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Chehalis River near Adna",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "ahuw1",
        "latitude": "46.536111",
        "longitude": "-120.472222",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Ahtanum Creek at Union Gap",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "albo3",
        "latitude": "44.638611",
        "longitude": "-123.106978",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Albany",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "amrw1",
        "latitude": "46.977778",
        "longitude": "-121.167500",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "American River (WA) near Nile",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "asto3",
        "latitude": "46.208333",
        "longitude": "-123.766667",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Columbia River at Tongue Pt near Astoria",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-72afe9"
    },
    {
        "lid": "aubw1",
        "latitude": "47.312500",
        "longitude": "-122.202778",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Green River (WA) near Auburn",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "auro3",
        "latitude": "45.233333",
        "longitude": "-122.750278",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Pudding River at Aurora",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "azao3",
        "latitude": "42.824843",
        "longitude": "-123.178949",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Cow Creek near Azalea",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "bcdw1",
        "latitude": "46.772222",
        "longitude": "-122.923056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Skookumchuck River near Bucoda",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "bdgo3",
        "latitude": "44.726389",
        "longitude": "-120.300833",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Bridge Creek near Mitchell",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "beao3",
        "latitude": "45.266667",
        "longitude": "-123.845833",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Nestucca River near Beaver",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "beno3",
        "latitude": "43.930278",
        "longitude": "-121.410833",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Deschutes River (OR) at Benham Falls",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "blkw1",
        "latitude": "46.830556",
        "longitude": "-123.184722",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Black River (WA) at Hwy 12",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "bskw1",
        "latitude": "47.312500",
        "longitude": "-122.164167",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Big Soos Creek near Auburn",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "btco3",
        "latitude": "44.953611",
        "longitude": "-120.136111",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Butte Creek near Fossil",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "bumw1",
        "latitude": "46.880000",
        "longitude": "-121.281111",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Bumping River below Bumping Dam",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "buso3",
        "latitude": "43.715833",
        "longitude": "-119.176667",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Silvies River near Burns",
        "wfo": "boi",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-00ff00"
    },
    {
        "lid": "cano3",
        "latitude": "45.244167",
        "longitude": "-122.687500",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Molalla River near Canby",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "casw1",
        "latitude": "46.274444",
        "longitude": "-122.912500",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Cowlitz River at Castle Rock",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "cenw1",
        "latitude": "46.711667",
        "longitude": "-122.978056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Chehalis River at Centralia",
        "wfo": "sew",
        "inundation": "1",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "cgmw1",
        "latitude": "46.776111",
        "longitude": "-123.034444",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Chehalis River near Grand Mound",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ciyw1",
        "latitude": "46.444167",
        "longitude": "-121.838889",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Cispus River near Randle",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "clew1",
        "latitude": "47.244562",
        "longitude": "-121.067864",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Yakima River at Cle Elum Outflow",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "ci-72afe9"
    },
    {
        "lid": "clfw1",
        "latitude": "46.900556",
        "longitude": "-121.018056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Naches River near Cliffdell",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "cmtw1",
        "latitude": "46.962500",
        "longitude": "-123.603333",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Chehalis River at Montesano",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "coco3",
        "latitude": "45.379722",
        "longitude": "-122.578056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Clackamas River near Oregon City",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "cogo3",
        "latitude": "42.823333",
        "longitude": "-123.124722",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Cow Creek above Azalea",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "coqo3",
        "latitude": "43.157942",
        "longitude": "-124.181794",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Coquille River at Coquille",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "coro3",
        "latitude": "44.566389",
        "longitude": "-123.256944",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Corvallis",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "crao3",
        "latitude": "43.750000",
        "longitude": "-121.783333",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Deschutes River (OR) below Crane Prairie Reservoir",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "crow1",
        "latitude": "46.806944",
        "longitude": "-123.118889",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Chehalis River at Rochester",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "crpo3",
        "latitude": "44.179167",
        "longitude": "-120.587778",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Crooked River (OR) above Prineville Reservoir",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "crpw1",
        "latitude": "46.939444",
        "longitude": "-123.313056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Chehalis River at Porter",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "crww1",
        "latitude": "46.661111",
        "longitude": "-122.982778",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Chehalis River at WWTP at Chehalis",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "ctaw1",
        "latitude": "46.730278",
        "longitude": "-122.953889",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Skookumchuck River at Centralia",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ctkw1",
        "latitude": "46.478611",
        "longitude": "-123.297222",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Chehalis River near Pe Ell",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "cvrw1",
        "latitude": "46.216667",
        "longitude": "-119.108056",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Columbia River at Clover Island",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "cwmo3",
        "latitude": "42.745278",
        "longitude": "-123.517222",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Cow Creek at Glendale",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "debo3",
        "latitude": "44.083056",
        "longitude": "-121.306667",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Deschutes River (OR) below Bend",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "deeo3",
        "latitude": "43.217894",
        "longitude": "-123.288680",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Deer Creek at Roseburg",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "deto3",
        "latitude": "44.722061",
        "longitude": "-122.250058",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "N Santiam River at Detroit Lake",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "dllo3",
        "latitude": "45.474722",
        "longitude": "-123.125000",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Tualatin River near Dilley",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "dotw1",
        "latitude": "46.617500",
        "longitude": "-123.276389",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Chehalis River near Doty",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "dsrw1",
        "latitude": "46.852222",
        "longitude": "-122.667500",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Deschutes River near Rainier",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "easw1",
        "latitude": "47.238889",
        "longitude": "-121.177778",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Yakima River at Easton",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ecdo3",
        "latitude": "43.640833",
        "longitude": "-123.298333",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Elk creek near Drain",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ekto3",
        "latitude": "43.586111",
        "longitude": "-123.554167",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Umpqua River near Elkton",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "elcw1",
        "latitude": "46.634722",
        "longitude": "-123.295556",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Elk Creek (WA) near Doty",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "esto3",
        "latitude": "45.300556",
        "longitude": "-122.354444",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Clackamas River near Estacada",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "eugo3",
        "latitude": "44.052500",
        "longitude": "-123.082778",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Eugene",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "ffxw1",
        "latitude": "47.028056",
        "longitude": "-122.031389",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Carbon River near Fairfax",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "frmo3",
        "latitude": "45.449444",
        "longitude": "-122.950278",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Tualatin River at Farmington",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "fsso3",
        "latitude": "45.703611",
        "longitude": "-123.755000",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Nehalem River near Foss",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "glio3",
        "latitude": "43.321508",
        "longitude": "-122.809499",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "North Umpqua River near Glide",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-00ff00"
    },
    {
        "lid": "glno3",
        "latitude": "42.804167",
        "longitude": "-123.609722",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "West Fork Cow Creek near Glendale",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "goso3",
        "latitude": "43.980556",
        "longitude": "-122.965278",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Coast Fork Willamette River at Goshen",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "gpuw1",
        "latitude": "47.305279",
        "longitude": "-121.849442",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Green River (WA) at Purification Plant",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "grrw1",
        "latitude": "46.355000",
        "longitude": "-123.581667",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Grays River near Rosburg",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "5",
        "icon": "sq-00ff00"
    },
    {
        "lid": "gsvo3",
        "latitude": "42.848889",
        "longitude": "-123.177778",
        "gauge_type": "0",
        "obs_status": "bdc2bb",
        "name": "Cow Creek at GALESVILLE RES",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-bdc2bb"
    },
    {
        "lid": "hahw1",
        "latitude": "47.283889",
        "longitude": "-121.796667",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Green River (WA) below Howard Hanson Dam",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "haro3",
        "latitude": "44.271390",
        "longitude": "-123.173900",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Harrisburg",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "hhdw1",
        "latitude": "47.277222",
        "longitude": "-121.792222",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Green River (WA) at Howard Hanson Reservoir",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "hlkw1",
        "latitude": "47.124167",
        "longitude": "-120.739167",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Yakima River at Horlick",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "hodo3",
        "latitude": "45.654722",
        "longitude": "-121.548889",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Hood River near Hood River",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "jaso3",
        "latitude": "43.998611",
        "longitude": "-122.905556",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Mid Fork Willamette River at Jasper",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "jffo3",
        "latitude": "44.714722",
        "longitude": "-123.014167",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Santiam River at Jefferson",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "kacw1",
        "latitude": "47.261389",
        "longitude": "-121.202222",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Yakima River at Kachess Outflow",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "kaho3",
        "latitude": "44.856667",
        "longitude": "-121.148611",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Warm Springs near Kahneeta Hot Springs",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "ci-72afe9"
    },
    {
        "lid": "keew1",
        "latitude": "47.321389",
        "longitude": "-121.335000",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Yakima River at Keechelus Outflow",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "kelw1",
        "latitude": "46.142500",
        "longitude": "-122.916111",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Cowlitz River at Kelso",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "kiow1",
        "latitude": "46.253611",
        "longitude": "-119.476944",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Yakima River at Kiona",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "klcw1",
        "latitude": "46.265000",
        "longitude": "-121.243889",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Klickitat River near Glenwood",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "lapo3",
        "latitude": "43.689167",
        "longitude": "-121.501667",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Little Deschutes River near La Pine",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "lnrw1",
        "latitude": "46.987500",
        "longitude": "-121.098611",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Little Naches River near Nile",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "lopw1",
        "latitude": "46.105556",
        "longitude": "-122.953889",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Columbia River at Longview",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "lrww1",
        "latitude": "45.905600",
        "longitude": "-122.738300",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Lewis River at Woodland",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "ltcw1",
        "latitude": "47.181944",
        "longitude": "-121.387500",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Green River (WA) above Twin Camp",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "mayw1",
        "latitude": "46.510556",
        "longitude": "-122.615000",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Cowlitz River below Mayfield Dam",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mcmo3",
        "latitude": "45.205556",
        "longitude": "-123.182500",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "South Yamhill River at McMinnville",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mczo3",
        "latitude": "44.069849",
        "longitude": "-122.771187",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "McKenzie River near Walterville",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "5",
        "icon": "sq-00ff00"
    },
    {
        "lid": "meho3",
        "latitude": "44.789167",
        "longitude": "-122.618611",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "N Santiam River at Mehama",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "mknw1",
        "latitude": "46.933611",
        "longitude": "-122.559722",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Nisqually River at McKenna",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mmiw1",
        "latitude": "47.146944",
        "longitude": "-121.858611",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River below Clearwater River",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "mmrw1",
        "latitude": "47.140833",
        "longitude": "-121.930000",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "White River at Mud Mtn. Dam - Outflow",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mnro3",
        "latitude": "44.313056",
        "longitude": "-123.296389",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Long Tom River at Monroe",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "mnsw1",
        "latitude": "47.011667",
        "longitude": "-123.654167",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Wynoochee River near Montesano",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "modo3",
        "latitude": "45.622068",
        "longitude": "-120.905620",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Deschutes River (OR) at Moody",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mono3",
        "latitude": "44.813889",
        "longitude": "-119.430556",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "North Fork John Day River near Monument",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mplo3",
        "latitude": "44.063333",
        "longitude": "-123.882778",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Siuslaw River near Mapleton",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mslw1",
        "latitude": "47.189444",
        "longitude": "-119.264722",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Crab Creek near Moses Lake",
        "wfo": "otx",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "mtno3",
        "latitude": "44.531389",
        "longitude": "-120.033611",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Mountain Creek (OR) near Mitchell",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "muco3",
        "latitude": "44.316389",
        "longitude": "-119.534722",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Murderers Creek near Dayville",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "myno3",
        "latitude": "43.068178",
        "longitude": "-124.107844",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "North Fk Coquille River near Myrtle Point",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "mypo3",
        "latitude": "43.065665",
        "longitude": "-124.147048",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "South Fk Coquille River at Myrtle Point",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "nacw1",
        "latitude": "46.746667",
        "longitude": "-120.768056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Naches River near Naches",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "nasw1",
        "latitude": "46.374167",
        "longitude": "-123.742222",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Naselle River near Naselle",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "neww1",
        "latitude": "46.620278",
        "longitude": "-122.943889",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Newaukum River near Chehalis",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "nisw1",
        "latitude": "46.752778",
        "longitude": "-122.082500",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Nisqually River near National",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "nspw1",
        "latitude": "47.328333",
        "longitude": "-123.242500",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "North Fork Skokomish River near Potlatch",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "ocho3",
        "latitude": "44.400000",
        "longitude": "-120.433333",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Ochoco Creek below Ochoco Reservoir",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "ocuo3",
        "latitude": "45.348056",
        "longitude": "-122.620556",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River above Falls at Oregon City",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "orco3",
        "latitude": "45.357500",
        "longitude": "-122.610833",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River below Falls at Oregon City",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "ortw1",
        "latitude": "47.039444",
        "longitude": "-122.206667",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Puyallup River near Orting",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "pacw1",
        "latitude": "46.613056",
        "longitude": "-121.678056",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Cowlitz River at Packwood",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "parw1",
        "latitude": "46.497222",
        "longitude": "-120.441667",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Yakima River near Parker",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "pero3",
        "latitude": "44.725952",
        "longitude": "-121.246994",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Deschutes River (OR) near Madras",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "phio3",
        "latitude": "44.525000",
        "longitude": "-123.334722",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Marys River near Philomath",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "pico3",
        "latitude": "45.544444",
        "longitude": "-119.311111",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Butter Creek near Pine City",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "pitw1",
        "latitude": "45.756667",
        "longitude": "-121.208889",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Klickitat River near Pitt",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "powo3",
        "latitude": "42.891667",
        "longitude": "-124.069444",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "South Fk Coquille River at Powers",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "prdw1",
        "latitude": "46.628889",
        "longitude": "-119.863611",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Columbia River below Priest Rapids Dam",
        "wfo": "otx",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "prto3",
        "latitude": "45.518333",
        "longitude": "-122.671111",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Portland",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "prvo3",
        "latitude": "44.113889",
        "longitude": "-120.794444",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Crooked River (OR) near Prineville",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "puyw1",
        "latitude": "47.208611",
        "longitude": "-122.325833",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Puyallup River at Puyallup",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "raww1",
        "latitude": "46.531900",
        "longitude": "-121.956900",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Cowlitz River at Randle",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "rdlo3",
        "latitude": "42.923611",
        "longitude": "-123.428333",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Cow Creek near Riddle",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "reeo3",
        "latitude": "43.705000",
        "longitude": "-124.095000",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Umpqua River at Reedsport",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "rsbo3",
        "latitude": "43.211111",
        "longitude": "-123.349722",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "South Umpqua River at Roseburg",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "rtro3",
        "latitude": "44.888889",
        "longitude": "-119.140278",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Middle Fork John Day River at Ritter",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "satw1",
        "latitude": "47.000833",
        "longitude": "-123.493611",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Satsop River near Satsop",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "scro3",
        "latitude": "43.350000",
        "longitude": "-122.727778",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Steamboat Creek near Glide",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "scww1",
        "latitude": "46.445000",
        "longitude": "-123.081111",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "South Fork Chehalis Rver near Wildwood",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "sero3",
        "latitude": "44.793889",
        "longitude": "-120.005556",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "John Day River at Service Creek",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "sfjo3",
        "latitude": "44.423056",
        "longitude": "-119.540556",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "S. Fork John Day River near Dayville",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "shno3",
        "latitude": "45.863611",
        "longitude": "-122.796240",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Columbia River at St. Helens",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "silo3",
        "latitude": "44.715278",
        "longitude": "-123.888611",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Siletz River at Siletz",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "skrw1",
        "latitude": "46.784722",
        "longitude": "-122.717222",
        "gauge_type": "0",
        "obs_status": "ffff00",
        "name": "Skookumchuck River at Skookumchuck Reservoir",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-ffff00"
    },
    {
        "lid": "slmo3",
        "latitude": "44.944167",
        "longitude": "-123.042500",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Willamette River at Salem",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "sndo3",
        "latitude": "45.448611",
        "longitude": "-122.245000",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Sandy River near Bull Run",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "5",
        "icon": "sq-00ff00"
    },
    {
        "lid": "snro3",
        "latitude": "43.672222",
        "longitude": "-119.670833",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Silver Creek near Riley",
        "wfo": "boi",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "spew1",
        "latitude": "47.139722",
        "longitude": "-122.091389",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "South Prairie Creek at South Prairie",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "spro3",
        "latitude": "44.093056",
        "longitude": "-122.956111",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Mohawk River (OR) near Springfield",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "sqso3",
        "latitude": "44.287778",
        "longitude": "-121.543333",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Whychus Creek near Sisters",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "srcw1",
        "latitude": "47.316111",
        "longitude": "-123.236944",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Skokomish River at Combined Forks Virtual Gage",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-00ff00"
    },
    {
        "lid": "srdo3",
        "latitude": "43.783889",
        "longitude": "-123.468889",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Smith River near Drain",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "srpw1",
        "latitude": "47.310000",
        "longitude": "-123.175833",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Skokomish River near Potlatch",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "5",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ssuw1",
        "latitude": "47.340556",
        "longitude": "-123.278889",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "South Fork Skokomish River near Union",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "suro3",
        "latitude": "42.951944",
        "longitude": "-123.334722",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "South Umpqua River near Riddle",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "suvo3",
        "latitude": "44.782500",
        "longitude": "-123.234722",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Luckiamute River near Suver",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "syco3",
        "latitude": "45.477500",
        "longitude": "-122.508333",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Johnson Creek near Sycamore",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "ticw1",
        "latitude": "46.666667",
        "longitude": "-121.000000",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Tieton River at Tieton Headworks",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "tido3",
        "latitude": "44.385954",
        "longitude": "-123.831778",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Alsea River near Tidewater",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "tilo3",
        "latitude": "42.930556",
        "longitude": "-122.947222",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "South Umpqua River near Tiller",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "tilw1",
        "latitude": "46.595556",
        "longitude": "-122.458333",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Tilton River near Cinebar",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "tlmo3",
        "latitude": "45.475833",
        "longitude": "-123.725000",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Wilson River near Tillamook",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "tlyo3",
        "latitude": "45.125000",
        "longitude": "-122.072222",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Clackamas River above Three Lynx Creek",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "tnaw1",
        "latitude": "47.246389",
        "longitude": "-120.861111",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Teanaway River near Cle Elum",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "topw1",
        "latitude": "46.311111",
        "longitude": "-120.786944",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Toppenish Creek near Fort Simcoe",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "totw1",
        "latitude": "46.335000",
        "longitude": "-122.840833",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Toutle River at Tower Road near Silver Lake",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "trao3",
        "latitude": "45.446389",
        "longitude": "-123.709167",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Trask River near Tillamook",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "5",
        "icon": "sq-00ff00"
    },
    {
        "lid": "umao3",
        "latitude": "45.902910",
        "longitude": "-119.326962",
        "gauge_type": "1",
        "obs_status": "72afe9",
        "name": "Umatilla River at Umatilla",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "ci-72afe9"
    },
    {
        "lid": "umtw1",
        "latitude": "46.862626",
        "longitude": "-120.480067",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Yakima River at Umtanum",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "vapw1",
        "latitude": "45.631389",
        "longitude": "-122.696389",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Columbia River at Vancouver",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "veno3",
        "latitude": "45.806944",
        "longitude": "-123.281944",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Nehalem River near Vernonia",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "5",
        "icon": "sq-00ff00"
    },
    {
        "lid": "vido3",
        "latitude": "44.125278",
        "longitude": "-122.469444",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "McKenzie River near Vida",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "wabw1",
        "latitude": "47.266109",
        "longitude": "-122.228615",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River near Auburn",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wauo3",
        "latitude": "46.161111",
        "longitude": "-123.408333",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Columbia River at Wauna",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "wbcw1",
        "latitude": "47.173889",
        "longitude": "-122.008056",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River above Boise Ck",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wico3",
        "latitude": "43.683333",
        "longitude": "-121.683333",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Deschutes River (OR) below Wickiup Reservoir",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "wilw1",
        "latitude": "46.651111",
        "longitude": "-123.651667",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "Willapa River at Willapa",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "wino3",
        "latitude": "43.283333",
        "longitude": "-123.352778",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "North Umpqua River at Winchester Dam",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "wnro3",
        "latitude": "43.270833",
        "longitude": "-123.411389",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "North Umpqua River near Winchester",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "wpcw1",
        "latitude": "47.260277",
        "longitude": "-122.237220",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River at Pacific",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wraw1",
        "latitude": "47.275000",
        "longitude": "-122.206667",
        "gauge_type": "1",
        "obs_status": "00ff00",
        "name": "White River at R St. Auburn",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "1",
        "icon": "ci-00ff00"
    },
    {
        "lid": "wrdw1",
        "latitude": "47.235556",
        "longitude": "-122.236111",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River near Dieringer",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wrpw1",
        "latitude": "47.271388",
        "longitude": "-122.218880",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River at Roegner Pk. nr Auburn",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wslo3",
        "latitude": "45.350833",
        "longitude": "-122.675000",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Tualatin River at West Linn",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "wsno3",
        "latitude": "43.133333",
        "longitude": "-123.397222",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "South Umpqua River near Winston",
        "wfo": "mfr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "wstw1",
        "latitude": "47.250277",
        "longitude": "-122.242200",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "White River near Sumner",
        "wfo": "sew",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\",\"precip\":\"false\"}",
        "state": "WA",
        "fcststatus": "4",
        "icon": "di-72afe9"
    },
    {
        "lid": "wtlo3",
        "latitude": "44.497778",
        "longitude": "-122.821944",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "S. Santiam River at Waterloo",
        "wfo": "pqr",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "1",
        "icon": "sq-00ff00"
    },
    {
        "lid": "yoko3",
        "latitude": "45.677222",
        "longitude": "-119.035833",
        "gauge_type": "0",
        "obs_status": "72afe9",
        "name": "Umatilla River near Yoakum",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "OR",
        "fcststatus": "6",
        "icon": "di-72afe9"
    },
    {
        "lid": "yumw1",
        "latitude": "47.191231",
        "longitude": "-120.947027",
        "gauge_type": "0",
        "obs_status": "00ff00",
        "name": "Yakima River at Cle Elum",
        "wfo": "pdt",
        "inundation": "0",
        "hsa_display": "{\"stage_flow\":\"true\", \"precip\":\"true\"}",
        "state": "WA",
        "fcststatus": "6",
        "icon": "di-00ff00"
    }]
}

var waterStationPointsArray = oldJson.points.map(function (item) {
    return {
        type: 'Feature',
        geometry: {
            type: 'Point',
            "coordinates": [+item.longitude, +item.latitude]
        },
        properties: {
            name: item.name,
            lid: item.lid,
            //gauge_type: item.gauge_type,
            //wfo: item.wfo,
            //state: item.state,
            //fcststatus: item.fcststatus
        }
    };
})

var geoJsonObj = {
    "type": "FeatureCollection",
    "features": waterStationPointsArray
}

console.log(JSON.stringify(geoJsonObj));